### ISSUE TITLE
[FEATURE] 顶部点击滚到顶部

### ISSUE THREAD

**Issue by OnTheThirdDay** [BYR-App-Dev/byr_mobile_app#2]
**功能需求**
方便用户快速回到帖子起始位置

**方案**
点状态栏或点AppBar滚回顶部

**替代方案**
返回顶部按钮，在跳页按钮附近

**补充信息**
来自论坛用户反馈
https://bbs.byr.cn/#!article/Picture/3266927?s=3267003

**Comment by malikwang** [comment]
跳页附近也可以  更方便操作
