### ISSUE TITLE
[FEATURE] 页面中部滑动返回

### ISSUE THREAD

**Issue by OnTheThirdDay** [BYR-App-Dev/byr_mobile_app#3]
**功能需求**
目前是边缘区域滑动返回，右手用户可能返回较费力

**方案**
增加页面中部滑动也可返回

**替代方案**
无

**补充信息**
来自论坛用户反馈
https://bbs.byr.cn/#!article/Picture/3266927?s=3267000

**Comment by malikwang** [comment]
@OnTheThirdDay  https://pub.dev/packages/cupertino_back_gesture

**Comment by malikwang** [comment]
看了一下源代码 感觉就是修改了原来./flutter/lib/src/cupertino/route.dart 
第692行 dragAreaWidth = max(dragAreaWidth, _kBackGestureWidth);
把_kBackGestureWidth改个很大的值就行了
可能安卓系统没有类似的手势习惯，安卓就酌情添加

**Comment by malikwang** [comment]
已添加该功能 FullscreenBackPageRoute
