### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by zisding** [BYR-App-Dev/byr_mobile_app#5]
**描述bug**
1. 登录账号
2. 登出账号
3. 关闭 APP
4. 重新打开 APP 依然在线。

**复现**
请描述如何复现该bug
1. 登录账号
2. 登出账号
3. 关闭 APP
4. 重新打开 APP 依然在线。

**预期的效果**
无法退出账号

**Comment by OnTheThirdDay** [comment]
Android在2021年5月1日更新中已修复。iOS在下次更新中修复。
