### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by waruto210** [BYR-App-Dev/byr_mobile_app#6]
**描述问题**
黑名单可拉黑自己导致看不到自己发的文章和评价，但是电脑网页版可以看见。

**补充信息**
无

**Comment by OnTheThirdDay** [comment]
自己拉黑自己导致看不到自己发的帖属于用户可以预期到的结果。

**Comment by waruto210** [comment]
> 自己

我是觉得允许拉黑自己这个feature很迷惑

**Comment by OnTheThirdDay** [comment]
网页版黑名单等于客户端的消息黑名单，是基于账号的功能，区别于客户端的内容黑名单。内容黑名单是基于客户端的功能，切换账号会导致消息黑名单的变化，但不会导致内容黑名单的变化，所以内容黑名单能否添加并不会对账号进行判断，即 在账号A时拉黑账号B，切换到账号B，账号B还会在内容黑名单中，因为这个黑名单是属于客户端而非账号。

简而言之：后台没这个api，客户端自己加的功能，判断账号会导致黑名单inconsistency，所以就不判断了。
